name: Build and Deploy

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:  # Esto permite que el workflow se ejecute manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Move JAR to build folder
      run: mv target/*.jar build/

    - name: Commit and Push JAR to GitHub
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add build/*.jar
        git commit -m "Add JAR file to build folder"
        git push origin main
